login/urls.py
from django.urls import path
from django.conf.urls import url
from . import views as login_views
from operation import views as op_views
import datetime

urlpatterns = [
    path('', op_views.HomeListView.as_view(), name='home'),
    path('home/', op_views.HomeListView.as_view(), name='home'),
    path('home/test', op_views.HomeTestListView.as_view(), name='homeTest'),
    path('operation/', op_views.operation, name='operation'),
    path('history/', op_views.HistoryListView.as_view(), name='history'),
    path('domain/<str:domain>/', op_views.DomainListView.as_view(), name='domain'),
    path('result/<slug:pk>', op_views.ResultListView.as_view(), name='result'),
    path('application/<slug:id>', op_views.application, name='application'),
    path('plannedmain/<slug:id>', op_views.plannedmain, name='plannedmain'),
    path('edit/<slug:id>', op_views.update, name='edit'),
    path('export/', op_views.export, name='export'),
    path('summary/', op_views.chart, name='summary'),
    path('dateInput/', op_views.dateInput, name='dateInput'),
    path('dateInput/success/', op_views.DateInputSuccessListView.as_view(), name='dateInputSuccess'),
    path('api/operation/', op_views.apiOps, name='apiOps'),
    path('api/dateinput/', op_views.apiDate, name='apiDate'),
]

nightwork/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from login import views as login_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', login_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('', include('login.urls')),
]

operation/models.py
from django.db import models
import datetime

# Create your models here.

def filename(instance, filename):
    filebase, extension = filename.split(".")
    return "%s-%s.%s" %(instance.startdate, instance.subject, extension)

class SpecialDate(models.Model):
    name            = models.CharField(max_length=255)
    startdate       = models.DateField()
    enddate         = models.DateField()

class Operation(models.Model):
    name            = models.CharField(max_length=255)
    phone           = models.CharField(max_length=255)
    domain          = models.CharField(max_length=255)
    category        = models.CharField(max_length=255)
    startdate       = models.DateField()
    starttime       = models.TimeField(default=datetime.time(00,00))
    enddate         = models.DateField()
    endtime         = models.TimeField(default=datetime.time(5,00))
    duration        = models.TextField()
    location        = models.CharField(max_length=255)
    subject         = models.TextField()
    reason_type     = models.CharField(max_length=255)
    reason          = models.TextField()
    impact          = models.TextField(default='No Service Impact')
    remarks         = models.CharField(max_length=255, default='N/A')
    vendor          = models.CharField(blank=True, max_length=255)
    vendor_phone    = models.CharField(blank=True, max_length=255)
    mop             = models.FileField(null=True, blank=True, upload_to=filename)

    @property
    def get_duration(self):
        end_minutes = self.endtime.hour*60 + self.endtime.minute
        start_minutes = self.starttime.hour*60 + self.starttime.minute
        duration_min = end_minutes - start_minutes
        if (duration_min < 0):
            duration_min = 1440 + duration_min
        return duration_min

    def save(self, *arg, **kwargs):
        self.duration = self.get_duration
        super(Operation, self).save(*arg, **kwargs)

operation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView
from django.db.models import Count
from .models import Operation, SpecialDate
from django.http import HttpResponse
from .forms import OperationForm, RawOperationForm, SpecialDateForm
from django.contrib import messages
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.db.models.functions import ExtractMonth, ExtractYear
from django.shortcuts import render
from django.template.loader import render_to_string
from django.template import Context
from django.core.mail import send_mail, EmailMultiAlternatives
import json
import calendar
import csv
import os
from datetime import date

class AdminStaffRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

# Create your views here.
@login_required(login_url="/login/")
def plannedmain(request, id=None):
    if request.user.is_authenticated:
        username = request.user.get_username()
    form = Operation.objects.get(id=id)
    subject = "[Planned Maintenance]" + form.subject + " on " + str(form.startdate)
    context = {
        'form': form
    }
    msg_html = render_to_string('plannedmain.html', context)
    subject, from_email, to = subject, 'stephencheung@hk.chinamobile.com', 'stephencheung@hk.chinamobile.com'
    html_content = msg_html
    msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
    msg.attach_alternative(html_content, "text/html")
    # msg.send()
    return render(request, 'plannedmain.html', context)

@login_required(login_url="/login/")
def application(request, id=None):
    form = Operation.objects.get(id=id)
    subject = "Application for " + form.subject + " on " + str(form.startdate)
    mop = form.mop
    context = {
        'form': form
    }
    msg_html = render_to_string('application.html', context)
    subject, from_email, to = subject, 'stephencheung@hk.chinamobile.com', 'stephencheung@hk.chinamobile.com'
    html_content = msg_html
    filename = "/var/mycode/nightwork/file/" + str(form.mop)
    # msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
    msg.attach_alternative(html_content, "text/html")
    msg.attach_file(filename)
    # msg.send()
    return render(request, 'application.html', context)    

@login_required(login_url="/login/")
def operation(request):
    initial_data = {
        'remarks' : "N/A",
        'impact': "No Service Impact"
    }
    form = RawOperationForm(request.POST or None, request.FILES or None, initial=initial_data)
    if form.is_valid():
        new = Operation.objects.create(**form.cleaned_data)
        id = new.id
        messages.success(request, "Operation Created")
        return redirect('result', pk=id)
    else:
        print(form.errors)
    context = {
        "form": form
    }
    return render(request, "operation.html", context)

@login_required(login_url="/login/")
def update(request, id=None):
    instance = get_object_or_404(Operation, pk=id)
    form = OperationForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Operation Saved")
        return redirect('result', pk=id)
    context  = {
        "form": form,
    } 
    return render(request, "update.html", context)

def apiOps(request):
    if  request.method == 'DELETE':
        data = json.loads(request.body.decode('utf-8'))
        id = data['id']
        Operation.objects.filter(id=id).delete()
        return JsonResponse({'msg':'true'})
    else:
        return JsonResponse({'msg':'fail'})        

def apiDate(request):
    if  request.method == 'DELETE':
        data = json.loads(request.body.decode('utf-8'))
        id = data['id']
        SpecialDate.objects.filter(id=id).delete()
        return JsonResponse({'msg':'true'})
    else:
        return JsonResponse({'msg':'fail'})        

@login_required(login_url="/login/")
def dateInput(request):
    if  request.method == 'POST':
        formDate = SpecialDateForm(request.POST or None, request.FILES or None)
        form = RawOperationForm(request.POST or None, request.FILES or None)
        if formDate.is_valid():
            newDate = SpecialDate.objects.create(**formDate.cleaned_data)
            dateId = newDate.id
            formDate = SpecialDate.objects.get(id=dateId)
            return redirect('/dateInput/success/')
        else:
            print(formDate.errors)
            
        if form.is_valid():
            newOp = Operation.objects.create(**form.cleaned_data)
            opId = newOp.id
            form = Operation.objects.get(id=opId)
            context = {
                'form': form
            }
            return redirect('result', pk=opId)
        else:
            print(form.errors)
        
    return render(request, "date_input.html",{
        'formDate': SpecialDateForm(request.POST or None),
        'form': RawOperationForm(request.POST or None)
    })


def chart(request):
    if  request.method == 'POST':
        form = RawOperationForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            new = Operation.objects.create(**form.cleaned_data)
            id = new.id
            form = Operation.objects.get(id=id)
            subject = "A new operation has just been created by " + form.name
            context = {
                'form': form
            }
            msg_html = render_to_string('notice.html', context)
            subject, from_email, to = subject, 'stephencheung@hk.chinamobile.com', 'stephencheung@hk.chinamobile.com'
            html_content = msg_html
            msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            # msg.send()
            messages.success(request, "Operation Created")
            return redirect('result', pk=id)
        else:
            print(form.errors)
    domains     = [] #/ operations by domain
    reasontypes = [] #/ operations by reasontype
    years       = []
    months      = []
    counts      = []
    data        = [] #/ sorted by domain
    data2       = [] #/ sorted by reasontype
    today       = date.today()
    last        = today.replace(year=today.year-1)
    startrange  = calendar.monthrange(today.year,today.month)[1]
    thisyear    = today.replace(day=startrange)
    lastyear    = last.replace(day=1)
    #startrange = find the last day of the month
    #thisyear   = replace "the day of today" with "the last day of the month"
    #lastyear   = replace the day with 1st day of the month
    #queryset: operation, 2020 by domain
    #queryset2: operation, 2020 by reasontype
    #queryset3: operation, sorted by year-month 
    queryset  = Operation.objects.all().values('domain').filter(startdate__year=today.year).annotate(total=Count('domain')).order_by('domain')
    queryset2 = Operation.objects.all().values('reason_type').filter(startdate__year=today.year).annotate(total=Count('reason_type')).order_by('reason_type')
    queryset3 = Operation.objects.all().values('startdate').filter(startdate__range=[lastyear,thisyear]).annotate(month=ExtractMonth('startdate'), year=ExtractYear('startdate')).values('month', 'year').annotate(count=Count('id')).values('month', 'year', 'count').order_by('year','month')
    op_count  = Operation.objects.all().filter(startdate__year=today.year).count()
    for domain in queryset.values_list('domain', flat=True):
        domains.append(domain)
    for total in queryset.values_list('total', flat=True):
        data.append(total)
    for month in queryset3.values_list('month', flat=True):
        months.append(str(calendar.month_abbr[month]))
    for year in queryset3.values_list('year', flat=True):
        years.append(str(year))
    for count in queryset3.values_list('count', flat=True):
        counts.append(count)
    for reason_type in queryset2.values_list('reason_type', flat=True):
        reasontypes.append(reason_type)
    for total in queryset2.values_list('total', flat=True):
        data2.append(total)
    period = [i + " " + j for i, j in zip(months, years)] 
    return render(request, "chart.html",{
        'count'      : op_count,
        'domain'     : domains,
        'data'       : data,
        'reason_type': reasontypes,
        'data2'      : data2,
        'period'     : period,
        'ym_count'   : counts,
        'form'       : RawOperationForm(request.POST or None)
    })


@login_required(login_url="/login/")
def export(request):
    response = HttpResponse(content_type='text/csv')
    now = datetime.datetime.now().strftime("%Y-%m-%d")
    response['Content-Disposition'] = 'attachment; filename="OperationSummary ({}).csv"'.format(str(now))
    writer   = csv.writer(response)
    writer.writerow([
        'name',
        'phone',
        'domain',
        'category',
        'startdate',
        'starttime',
        'enddate',
        'endtime',
        'location',
        'subject',
        'reason_type',
        'reason',
        'impact',
        'remarks',
        'vendor',
        'vendor_phone',
        'mop',])
    
    for operation in Operation.objects.all().values_list(
        'name',
        'phone',
        'domain',
        'category',
        'startdate',
        'starttime',
        'enddate',
        'endtime',
        'location',
        'subject',
        'reason_type',
        'reason',
        'impact',
        'remarks',
        'vendor',
        'vendor_phone',
        'mop',
    ):
        writer.writerow(operation)

    return response

class HistoryListView(AdminStaffRequiredMixin, ListView):
    login_url = '/login/'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link rel="stylesheet" href="{% static 'nightwork/bootstrap.min.css' %}" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'nightwork/main.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'nightwork/cloud2.png' %}"/>
    <script src="{% static 'nightwork/jquery-3.4.1.min.js' %}"></script>

    {% if title %}
        <title>NRM Schedule - {{ title }}</title>
    {% else %}
        <title>NRM Schedule</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar-expand-md navbar-dark bg-cmhk fixed-top">
        <div class=" header-container">
            {% if user.is_authenticated %}
              <a class="navbar-brand mr-4" href="{% url 'home' %}"><img style="height:45px;" hspace="20" src="{% static 'nightwork/cloud.png' %}">NRM Schedule</a>
            {% else %}
              <a class="navbar-brand mr-4" href="{% url 'home' %}"><img style="height:45px;" hspace="20" src="{% static 'nightwork/cloud.png' %}">NRM Schedule</a>
            {% endif %}
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'home' %}"><img src="{% static 'nightwork/home.png' %}"/> Home</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'home' %}"><img src="{% static 'nightwork/home.png' %}"/> Home</a>
              {% endif %}
              <a class="nav-item nav-link" href="{% url 'summary' %}"><img src="{% static 'nightwork/chart.png' %}"/> Summary</a>
            </div>
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link"><img src="{% static 'nightwork/user.png' %}"/> {{ user.username }}</a>
                <a class="nav-item nav-link" "href=javascript:;" id="operation"><img src="{% static 'nightwork/create.png' %}"/> New Operation</a>
                <a class="nav-item nav-link" href="{% url 'dateInput' %}"><img src="{% static 'nightwork/calendar.png' %}"/> Date Input</a>
                <a class="nav-item nav-link" href="{% url 'history' %}"><img src="{% static 'nightwork/history.png' %}"/> History</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}"><img src="{% static 'nightwork/logout.png' %}"/> Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}"><img src="{% static 'nightwork/login.png' %}"/> Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="body-container">

        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{ message}}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
    </main>


 <div id="fullCalModal2" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header"><meta name="c-token" content="{!! csrf_token() !!}" />
        <h4 class="modal-title">Create Operation</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <form class="form-group" method='POST' enctype='multipart/form-data'>{% csrf_token %}
          <div class="row">
              <div class="col-md-4 mb-4">Name</div>
              <div class="col-md-6 mb-4">{{ form.name }}</div>
          </div>
          <div class="row">
              <div class="col-md-4 mb-4">Phone</div>
              <div class="col-md-6 mb-4">{{ form.phone }}</div>
          </div>
          <div class="row">
              <div class="col-md-2 mb-4">Domain</div>       
              <div class="col-md-4 mb-4">{{ form.domain }}</div>
              <div class="col-md-2 mb-4">Category</div>
              <div class="col-md-3 mb-4">{{ form.category }}</div>
          </div>
          <div class="row">
              <div class="col-md-2 mb-4">Start Date</div>
              <div class="col-md-4 mb-4">{{ form.startdate }}</div>
              <div class="col-md-2 mb-4">End Date</div>
              <div class="col-md-3 mb-4">{{ form.enddate }}</div>
          </div>
          <div class="row">
              <div class="col-md-2 mb-4">Start Time</div>
              <div class="col-md-4 mb-4">{{ form.starttime }}</div>
              <div class="col-md-2 mb-4">End Time</div>
              <div class="col-md-3 mb-4">{{ form.endtime }}</div>
          </div>
          <div class="row">
              <div class="col-md-4 mb-4">Location</div>
              <div class="col-md-6 mb-4">{{ form.location }}</div>
          </div>
          <div class="row">
              <div class="col-md-4 mb-4">Subject</div>
              <div class="col-md-6 mb-4">{{ form.subject }}</div>
          </div>
          <div class="row">
              <div class="col-md-4 mb-4">Reason Type</div>
              <div class="col-md-6 mb-4">{{ form.reason_type }}</div>
          </div>
          <div class="row">
              <div class="col-md-4 mb-4">Reason</div>
              <div class="col-md-6 mb-4">{{ form.reason }}</div>
          </div>
          <div class="row">
              <div class="col-md-4 mb-4">Impact</div>
              <div class="col-md-6 mb-4">{{ form.impact }}</div>
          </div>
          <div class="row">
              <div class="col-md-4 mb-4">Remarks</div>
              <div class="col-md-6 mb-4">{{ form.remarks }}</div>
          </div>
          <div class="row">
              <div class="col-md-4 mb-4">Vendor Staff Name (Optional)</div>
              <div class="col-md-6 mb-4">{{ form.vendor }}</div>
          </div>
          <div class="row">
              <div class="col-md-4 mb-4">Vendor Phone (Optional)</div>
              <div class="col-md-6 mb-4">{{ form.vendor_phone }}</div>
          </div>
          <div class="row">
              <div class="col-md-4 mb-4">MOP Upload</div>
              <div class="col-md-6 mb-4">{{ form.mop }}</div>
          </div>
    <div class="row">
    <div class="col text-center"> 
        <input type='submit' class="btn btn-secondary" value='Create' />
    </div>
    </div>
    </form>
    </div>
    </div>
    </div>
    <script src="{% static 'nightwork/popper.min.js' %}" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="{% static 'nightwork/bootstrap2.min.js' %}" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script>
$('#operation').click(function(event){
  $('#fullCalModal2').modal();
 });
    $("#id_phone").val("92049358");
    $("#id_name").change(function(){
        if ($('#id_name option:selected').text() == "Teddy Kwong"){
            $("#id_phone").val("92044001");
        } else if ($('#id_name option:selected').text() == "Rick Ching"){
            $("#id_phone").val("92047128");
        } else if ($('#id_name option:selected').text() == "David Lun"){
            $("#id_phone").val("92049174");
        } else if ($('#id_name option:selected').text() == "Matt So"){
            $("#id_phone").val("92047569");
        } else if ($('#id_name option:selected').text() == "Nancy Nie"){
            $("#id_phone").val("92049328");
        } else if ($('#id_name option:selected').text() == "Leo Liu"){
            $("#id_phone").val("68478592");
        } else if ($('#id_name option:selected').text() == "Stephen Cheung"){
            $("#id_phone").val("63592507");
        } else if ($('#id_name option:selected').text() == "Roger Liu"){
            $("#id_phone").val("92049358");
        } else if ($('#id_name option:selected').text() == "Billy Chan"){
            $("#id_phone").val("68478853");
        }});
</script>
</body>
</html>

templates/date_input.html
{% extends "base.html" %} {% load static %} {% block content%}
<head>
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'packages/core/main.css' %}"
  />
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'packages/daygrid/main.css' %}"
  />
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'packages/timegrid/main.css' %}"
  />
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'packages/list/main.css' %}"
  />

  <script src="{% static 'packages/core/main.js' %}"></script>
  <script src="{% static 'packages/interaction/main.js' %}"></script>
  <script src="{% static 'packages/daygrid/main.js' %}"></script>
  <script src="{% static 'packages/timegrid/main.js' %}"></script>
  <script src="{% static 'packages/list/main.js' %}"></script>
  <script src="{% static 'nightwork/jquery-3.4.1.min.js' %}"></script>
</head>

<legend class="border-bottom mb-8">Special Date Input</legend>
<p style="text-align: right; margin-bottom: 5px">
  <a href="{% url 'dateInputSuccess' %}">Special Date List</a>
</p>

<form class="form-group" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4 mb-4">Name</div>
    <div class="col-md-6 mb-4">{{ formDate.name }}</div>
  </div>
  <div class="row">
    <div class="col-md-2 mb-4">Start Date</div>
    <div class="col-md-4 mb-4">{{ formDate.startdate }}</div>
    <div class="col-md-2 mb-4">End Date</div>
    <div class="col-md-3 mb-4">{{ formDate.enddate }}</div>
  </div>
  <div class="row">
    <div class="col text-center">
      <input type="submit" class="btn btn-secondary" value="Create" />
    </div>
  </div>
</form>

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sent!</title>
</head>
<body>
    <h1>Sent</h1>
</body>
</html>

templates/operation.html
{% extends "base.html" %}
{% load static %}
{% block content%}
<head>

<link rel="stylesheet" type="text/css" href="{% static 'packages/core/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'packages/daygrid/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'packages/timegrid/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'packages/list/main.css' %}">

<script src="{% static 'packages/core/main.js' %}"></script>
<script src="{% static 'packages/interaction/main.js' %}"></script>
<script src="{% static 'packages/daygrid/main.js' %}"></script>
<script src="{% static 'packages/timegrid/main.js' %}"></script>
<script src="{% static 'packages/list/main.js' %}"></script>
<script src="{% static 'nightwork/jquery-3.4.1.min.js' %}"></script>
</head>

<legend class="border-bottom mb-8">Operation Details</legend>

 <div id="fullCalModal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

    <form class="form-group" method='POST' enctype='multipart/form-data'>{% csrf_token %}
    <div class="row">
        <div class="col-md-4 mb-4">Name</div>
        <div class="col-md-6 mb-4">{{ form.name }}</div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-4">Phone</div>
        <div class="col-md-6 mb-4">{{ form.phone }}</div>
    </div>
    <div class="row">
        <div class="col-md-2 mb-4">Domain</div>       
        <div class="col-md-4 mb-4">{{ form.domain }}</div>
        <div class="col-md-2 mb-4">Category</div>
        <div class="col-md-3 mb-4">{{ form.category }}</div>
    </div>
    <div class="row">
        <div class="col-md-2 mb-4">Start Date</div>
        <div class="col-md-4 mb-4">{{ form.startdate }}</div>
        <div class="col-md-2 mb-4">End Date</div>
        <div class="col-md-3 mb-4">{{ form.enddate }}</div>
    </div>
    <div class="row">
        <div class="col-md-2 mb-4">Start Time</div>
        <div class="col-md-4 mb-4">{{ form.starttime }}</div>
        <div class="col-md-2 mb-4">End Time</div>
        <div class="col-md-3 mb-4">{{ form.endtime }}</div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-4">Location</div>
        <div class="col-md-6 mb-4">{{ form.location }}</div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-4">Subject</div>
        <div class="col-md-6 mb-4">{{ form.subject }}</div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-4">Reason Type</div>
        <div class="col-md-6 mb-4">{{ form.reason_type }}</div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-4">Reason</div>
        <div class="col-md-6 mb-4">{{ form.reason }}</div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-4">Impact</div>
        <div class="col-md-6 mb-4">{{ form.impact }}</div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-4">Remarks</div>
        <div class="col-md-6 mb-4">{{ form.remarks }}</div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-4">Vendor Staff Name (Optional)</div>
        <div class="col-md-6 mb-4">{{ form.vendor }}</div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-4">Vendor Phone (Optional)</div>
        <div class="col-md-6 mb-4">{{ form.vendor_phone }}</div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-4">MOP Upload</div>
        <div class="col-md-6 mb-4">{{ form.mop }}</div>
    </div>
    <div class="row">
    <div class="col text-center"> 
        <input type='submit' class="btn btn-secondary" value='Create' />
    </div>
    </div>
    </form>
    </div>
    </div>
    </div>
    
<script>
        $(document).ready(function() {
             $('#fullCalModal').modal();
        });
    $("#id_phone").val("92049358");
    $("#id_name").change(function(){
        if ($('#id_name option:selected').text() == "Teddy Kwong"){
            $("#id_phone").val("92044001");
        } else if ($('#id_name option:selected').text() == "Matt So"){
            $("#id_phone").val("92047569");
        } else if ($('#id_name option:selected').text() == "Nancy Nie"){
            $("#id_phone").val("92049328");
        } else if ($('#id_name option:selected').text() == "Leo Liu"){
            $("#id_phone").val("68478592");
        } else if ($('#id_name option:selected').text() == "Stephen Cheung"){
            $("#id_phone").val("63592507");
        } else if ($('#id_name option:selected').text() == "Roger Liu"){
            $("#id_phone").val("92049358");
        }
        
    });
</script>

{% endblock %}